### ISSUE TITLE
Pinned tabs collapse

### ISSUE THREAD

**Issue by rayzorben** [mcortt/FirefoxJS#1]
Great addition, works well, except that pinned tabs will collapse into a single row when expanded, which means if you put the mouse over a tab to close it, it now jumps up. Would be nice to have an option to keep pinned tabs one per row.

![image](https://github.com/user-attachments/assets/43970495-99e4-4c14-b21a-672dd1140c5f)
![image](https://github.com/user-attachments/assets/ff6c4058-8e8e-4a58-bf7f-6a24629483a2)

**Comment by mcortt** [comment]
Mozilla recently changed this on the sidebar. I'll look into a work around next week.

**Comment by mcortt** [comment]
On further review, I don't believe this is something I would be willing to tackle within this project, as it is outside the scope of the intended feature of this customization (auto expand/collapse on hover).
