### ISSUE TITLE
Expanded Tabs Background not working properly.

### ISSUE THREAD

**Issue by uzamapg** [mcortt/FirefoxJS#2]
Your JS was working fine and today it is kind of glitched. The background is not shifting with the expanded tabs.

![firefox_Wyjt0p01fW](https://github.com/user-attachments/assets/4ea38cff-386b-4d0e-b066-87bbb0a4b819)

**Comment by mcortt** [comment]
Are you using Mica on Windows? Also are you using the default system theme?

**Comment by uzamapg** [comment]
> Are you using Mica on Windows? Also are you using the default system theme?

Yes I am using Mica for Windows and it was working fine before. I am using your JS on nightly though, That might be the cause of the issue.

**Comment by mcortt** [comment]
Fixed in latest update. Re-download the sidebar.uc.mjs or add the following line under #sidebar-main at line 15/16

            background: var(--lwt-accent-color) !important;

**Comment by mcortt** [comment]
On a side note, I also fixed an issue with it not injecting the custom div on subsequent windows, which made the sidebar overlap the page when collapsed.

**Comment by mcortt** [comment]
nvm, fix didnt work. looking into further options.

**Comment by uzamapg** [comment]
Also while you're at it, If you don't mind, can you also add a transition to it so it opens and closes smoothly instead of being just an open close toggle.

**Comment by uzamapg** [comment]
It is fixed in your recent release. Thank you. You can close this if you want to.
